# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/radiant-tide-374309/pytorch-latest-gpu-v20221215@sha256:57df47770bd76e847d1f5b2d6ea473326363ac35d67941ac631c46caae739730
